---
title: "Continuous Development Models for Greenup Phenology"
author: "Bijan Seyednasrollah"
date: "4/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This docuemnt explains how the two-stage and three-stage phenology models are set up and structured. 

## Two-Stage Phenology Model
The two-stage model is based on only a single transition points: 'Onset'. And therefore, the two stages include: 1) pre-onset and 2) post-onset. Here, I expain the theoretical  framework for a Hierarchical Bayesian model that can simualte the process. 

We first define a latent development state where the greenup continuously develops:
\begin{equation}
h_{p,y,d+1}  = h_{p,y,d} + \delta h_{p,y,d}
\end{equation}

where $h_{p,y,d}$ is the latent state for pixel *p*, in year *y* and day *d*. $ \delta h_{p,y,d}$ is the latent state increament.
We use a exponential increment function that 

\begin{equation}
\delta h_{p,y,d} = e^{x_{p,y,d}\beta + \epsilon}(1 - h_{p,y,d}/h_{max})[T-T{base}]
\end{equation}

We set $h_{p,y,1} = 0$, and $h_{max} = 1$. To link the discrete observations (pre-onset/post-onset or True/False) to the continuous scale that the development happnes, we use a logit transformation:
\begin{equation}
logit(P_{p,y,d}) = \kappa + \lambda*h_{p,y,d}
\end{equation}

where $\kappa$ and $\lambda$ are the intercept and slope of the transformation and $P_{p,y,d}$ is the probablity that the onset occures at pixel *P* in year *y* and day *d*.
$P_{p,y,d}$ has the Bernoulli distribution:

\begin{equation}
Y_{p,y,d} \sim bernoulli(P_{p,y,d})
\end{equation}

where Y_{p,y,d} is the observed phenological stage for pixel *p* in year *y* and day *d*.

## Three-Stage Phenology Model

The two-stage model is based on only a single transition points: 'Onset'. And therefore, the two stages include: 1) pre-onset and 2) post-onset. Here, I expain the theoretical  framework for a Hierarchical Bayesian model that can simualte the process. 

